"""smp modules

Revision ID: 4e2e105eaaa3
Revises: audit0001
Create Date: 2026-06-26 10:37:34.741185+00:00
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4e2e105eaaa3'
down_revision: str | None = 'audit0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('asset_type', sa.Enum('host', 'server', 'workstation', 'network_device', 'router', 'switch', 'firewall', 'service', 'application', 'database', 'iot', 'cloud_resource', 'other', name='asset_type'), nullable=False),
    sa.Column('hostname', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('ip_bidx', sa.String(length=64), nullable=True),
    sa.Column('mac_address', sa.String(), nullable=True),
    sa.Column('operating_system', sa.String(length=128), nullable=True),
    sa.Column('os_version', sa.String(length=64), nullable=True),
    sa.Column('criticality', sa.Enum('low', 'medium', 'high', 'critical', name='asset_criticality'), nullable=False),
    sa.Column('environment', sa.Enum('production', 'staging', 'development', 'test', 'unknown', name='asset_environment'), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', 'decommissioned', 'quarantined', name='asset_status'), nullable=False),
    sa.Column('owner', sa.String(length=128), nullable=True),
    sa.Column('location', sa.String(length=128), nullable=True),
    sa.Column('tags', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('discovered_by', sa.Enum('manual', 'network_discovery', 'import_', name='discovery_source'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assets'))
    )
    op.create_index(op.f('ix_assets_asset_type'), 'assets', ['asset_type'], unique=False)
    op.create_index(op.f('ix_assets_criticality'), 'assets', ['criticality'], unique=False)
    op.create_index(op.f('ix_assets_ip_bidx'), 'assets', ['ip_bidx'], unique=False)
    op.create_index(op.f('ix_assets_name'), 'assets', ['name'], unique=False)
    op.create_index(op.f('ix_assets_status'), 'assets', ['status'], unique=False)
    op.create_table('alert_rules',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('rule_type', sa.Enum('vuln_severity', 'critical_asset_vuln', 'new_host', 'open_port', 'integrity_violation', 'brute_force', name='alert_rule_type'), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('severity', sa.Enum('low', 'medium', 'high', 'critical', name='alert_rule_severity'), nullable=False),
    sa.Column('params', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_alert_rules_created_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alert_rules')),
    sa.UniqueConstraint('name', name=op.f('uq_alert_rules_name'))
    )
    op.create_table('asset_software',
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=True),
    sa.Column('vendor', sa.String(length=128), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_asset_software_asset_id_assets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_asset_software'))
    )
    op.create_index(op.f('ix_asset_software_asset_id'), 'asset_software', ['asset_id'], unique=False)
    op.create_index(op.f('ix_asset_software_name'), 'asset_software', ['name'], unique=False)
    op.create_table('discovery_scans',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('targets', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=False),
    sa.Column('ports', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'failed', 'cancelled', name='scan_status'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hosts_found', sa.Integer(), nullable=False),
    sa.Column('summary', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_discovery_scans_created_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_discovery_scans'))
    )
    op.create_index(op.f('ix_discovery_scans_status'), 'discovery_scans', ['status'], unique=False)
    op.create_table('incidents',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.Enum('low', 'medium', 'high', 'critical', name='incident_severity'), nullable=False),
    sa.Column('status', sa.Enum('open', 'investigating', 'contained', 'resolved', 'closed', name='incident_status'), nullable=False),
    sa.Column('reporter_id', sa.Uuid(), nullable=True),
    sa.Column('assignee_id', sa.Uuid(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], name=op.f('fk_incidents_assignee_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], name=op.f('fk_incidents_reporter_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_incidents'))
    )
    op.create_index(op.f('ix_incidents_assignee_id'), 'incidents', ['assignee_id'], unique=False)
    op.create_index(op.f('ix_incidents_severity'), 'incidents', ['severity'], unique=False)
    op.create_index(op.f('ix_incidents_status'), 'incidents', ['status'], unique=False)
    op.create_table('vuln_scans',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('scope', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=True),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'failed', 'cancelled', name='vuln_scan_status'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('summary', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_vuln_scans_created_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vuln_scans'))
    )
    op.create_index(op.f('ix_vuln_scans_status'), 'vuln_scans', ['status'], unique=False)
    op.create_table('discovered_hosts',
    sa.Column('scan_id', sa.Uuid(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=False),
    sa.Column('hostname', sa.String(), nullable=True),
    sa.Column('open_ports', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('asset_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_discovered_hosts_asset_id_assets'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scan_id'], ['discovery_scans.id'], name=op.f('fk_discovered_hosts_scan_id_discovery_scans'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_discovered_hosts'))
    )
    op.create_index(op.f('ix_discovered_hosts_scan_id'), 'discovered_hosts', ['scan_id'], unique=False)
    op.create_table('findings',
    sa.Column('scan_id', sa.Uuid(), nullable=False),
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('cve_id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.Enum('none', 'low', 'medium', 'high', 'critical', name='vuln_severity'), nullable=False),
    sa.Column('cvss_score', sa.Float(), nullable=True),
    sa.Column('affected_software', sa.String(length=128), nullable=True),
    sa.Column('affected_version', sa.String(length=64), nullable=True),
    sa.Column('fixed_version', sa.String(length=64), nullable=True),
    sa.Column('remediation', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('open', 'confirmed', 'false_positive', 'remediated', 'accepted_risk', name='vuln_status'), nullable=False),
    sa.Column('references', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_findings_asset_id_assets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scan_id'], ['vuln_scans.id'], name=op.f('fk_findings_scan_id_vuln_scans'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_findings'))
    )
    op.create_index(op.f('ix_findings_asset_id'), 'findings', ['asset_id'], unique=False)
    op.create_index(op.f('ix_findings_cve_id'), 'findings', ['cve_id'], unique=False)
    op.create_index(op.f('ix_findings_scan_id'), 'findings', ['scan_id'], unique=False)
    op.create_index(op.f('ix_findings_severity'), 'findings', ['severity'], unique=False)
    op.create_index(op.f('ix_findings_status'), 'findings', ['status'], unique=False)
    op.create_table('incident_assets',
    sa.Column('incident_id', sa.Uuid(), nullable=False),
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_incident_assets_asset_id_assets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], name=op.f('fk_incident_assets_incident_id_incidents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('incident_id', 'asset_id', name=op.f('pk_incident_assets'))
    )
    op.create_table('incident_evidence',
    sa.Column('incident_id', sa.Uuid(), nullable=False),
    sa.Column('file_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], name=op.f('fk_incident_evidence_file_id_files'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], name=op.f('fk_incident_evidence_incident_id_incidents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('incident_id', 'file_id', name=op.f('pk_incident_evidence'))
    )
    op.create_table('incident_notes',
    sa.Column('incident_id', sa.Uuid(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=True),
    sa.Column('note_type', sa.String(length=32), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_incident_notes_author_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], name=op.f('fk_incident_notes_incident_id_incidents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_incident_notes'))
    )
    op.create_index(op.f('ix_incident_notes_incident_id'), 'incident_notes', ['incident_id'], unique=False)
    op.create_table('incident_alerts',
    sa.Column('incident_id', sa.Uuid(), nullable=False),
    sa.Column('alert_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['security_alerts.id'], name=op.f('fk_incident_alerts_alert_id_security_alerts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], name=op.f('fk_incident_alerts_incident_id_incidents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('incident_id', 'alert_id', name=op.f('pk_incident_alerts'))
    )
    # New AuditEventType values added for the SMP modules. On PostgreSQL the
    # column is a native ENUM, so extend the type; on SQLite it is an unenforced
    # VARCHAR, so no migration is needed.
    _new_audit_events = [
        "asset_created", "asset_updated", "asset_deleted", "scan_started",
        "scan_completed", "vulnerability_detected", "alert_triggered",
        "incident_created", "incident_updated",
    ]
    if op.get_bind().dialect.name == "postgresql":
        for _value in _new_audit_events:
            op.execute(f"ALTER TYPE audit_event_type ADD VALUE IF NOT EXISTS '{_value}'")
    op.add_column('security_alerts', sa.Column('related_asset_id', sa.Uuid(), nullable=True))
    op.add_column('security_alerts', sa.Column('source_ref', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_security_alerts_source_ref'), 'security_alerts', ['source_ref'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_security_alerts_source_ref'), table_name='security_alerts')
    op.drop_column('security_alerts', 'source_ref')
    op.drop_column('security_alerts', 'related_asset_id')
    # Note: PostgreSQL cannot drop enum values; the extra audit_event_type values
    # are left in place (harmless) on downgrade.
    op.drop_table('incident_alerts')
    op.drop_index(op.f('ix_incident_notes_incident_id'), table_name='incident_notes')
    op.drop_table('incident_notes')
    op.drop_table('incident_evidence')
    op.drop_table('incident_assets')
    op.drop_index(op.f('ix_findings_status'), table_name='findings')
    op.drop_index(op.f('ix_findings_severity'), table_name='findings')
    op.drop_index(op.f('ix_findings_scan_id'), table_name='findings')
    op.drop_index(op.f('ix_findings_cve_id'), table_name='findings')
    op.drop_index(op.f('ix_findings_asset_id'), table_name='findings')
    op.drop_table('findings')
    op.drop_index(op.f('ix_discovered_hosts_scan_id'), table_name='discovered_hosts')
    op.drop_table('discovered_hosts')
    op.drop_index(op.f('ix_vuln_scans_status'), table_name='vuln_scans')
    op.drop_table('vuln_scans')
    op.drop_index(op.f('ix_incidents_status'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_severity'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_assignee_id'), table_name='incidents')
    op.drop_table('incidents')
    op.drop_index(op.f('ix_discovery_scans_status'), table_name='discovery_scans')
    op.drop_table('discovery_scans')
    op.drop_index(op.f('ix_asset_software_name'), table_name='asset_software')
    op.drop_index(op.f('ix_asset_software_asset_id'), table_name='asset_software')
    op.drop_table('asset_software')
    op.drop_table('alert_rules')
    op.drop_index(op.f('ix_assets_status'), table_name='assets')
    op.drop_index(op.f('ix_assets_name'), table_name='assets')
    op.drop_index(op.f('ix_assets_ip_bidx'), table_name='assets')
    op.drop_index(op.f('ix_assets_criticality'), table_name='assets')
    op.drop_index(op.f('ix_assets_asset_type'), table_name='assets')
    op.drop_table('assets')
    # ### end Alembic commands ###
